### ISSUE TITLE
Alle billeder fra Newsfeed

### ISSUE THREAD

**Issue by Hi-Tone** [jacobbunk/famly-fetch#3]
Tak for en sindsyg god idé og script.

Vores dagpleje har uploaded rigtigt mange billeder, men har ikke tagged nogle, hvilket gør at det er en utroligt langsommelig process at skulle tagge sit barn først i hvert enkelt billede.

Er det muligt at der findes et andet API adgang istedet for 'tagged', så man kan downloade alle billeder i sin Newsfeed ?

**Comment by jacobbunk** [comment]
Der er jo newsfeed-API'et, man sikkert kan bygge noget ovenpå.

Min adgang til Famly er allerede lukket, så jeg kan nok desværre ikke bidrage med meget i dette repository længere. Du er meget velkommen til at lave et pull-request hvis du finder ud af at hive data ud den vej.
